package managementasset

import (
	_ "embed"
)

// embeddedManagementHTML holds the bundled management control panel HTML.
// This file is generated by running `npm run build` in the web/ directory.
// If the file doesn't exist at compile time, the embed will be empty.
//
//go:embed static/management.html
var embeddedManagementHTML []byte

// EmbeddedHTML returns the embedded management control panel HTML content.
// Returns nil if no embedded content is available.
func EmbeddedHTML() []byte {
	if len(embeddedManagementHTML) == 0 {
		return nil
	}
	return embeddedManagementHTML
}

// HasEmbeddedHTML returns true if embedded management HTML is available.
func HasEmbeddedHTML() bool {
	return len(embeddedManagementHTML) > 0
}
