package managementasset

import (
	"embed"
	"io/fs"
)

// embeddedDistFS holds the bundled management control panel dist directory.
// This directory is generated by running `npm run build` in the web/ directory.
//
//go:embed dist/*
var embeddedDistFS embed.FS

// DistFS returns a filesystem rooted at the dist directory.
// Returns nil if no embedded content is available.
func DistFS() fs.FS {
	subFS, err := fs.Sub(embeddedDistFS, "dist")
	if err != nil {
		return nil
	}
	return subFS
}

// HasEmbeddedDist returns true if embedded dist directory is available.
func HasEmbeddedDist() bool {
	entries, err := embeddedDistFS.ReadDir("dist")
	if err != nil {
		return false
	}
	return len(entries) > 0
}

// EmbeddedHTML returns the embedded index.html content for backward compatibility.
// Returns nil if no embedded content is available.
func EmbeddedHTML() []byte {
	data, err := embeddedDistFS.ReadFile("dist/index.html")
	if err != nil {
		return nil
	}
	return data
}

// HasEmbeddedHTML returns true if embedded index.html is available.
func HasEmbeddedHTML() bool {
	_, err := embeddedDistFS.ReadFile("dist/index.html")
	return err == nil
}
